### ISSUE TITLE
Add Committers

### ISSUE THREAD

**Issue by nikmd23** [nikmd23/CourtesyFlush#10]
Hi @justinvp & @simonpucher,

You guys have both submitted great pull requests (#7 & #9, respectively), but I've been too busy to review them and pull them in.

I apologize for that.

I don't see myself slowing down anytime soon, so I'd like to propose adding both of you as committers to this repository. You could review each others pull requests and help get them accepted.

If you'd like to continue to work on CourtesyFlush after that, then great, but you don't have to. I can help get a release out, or give you permissions to push to NuGet.org - whichever you'd prefer.

Thoughts?

**Comment by simonpucher** [comment]
Hi @nikmd23, this is an awesome project thanks for sharing with us! This is a great ides. Of course we can do a merge of the changes and commit everything to nuget.

**Comment by nikmd23** [comment]
Thanks @simonpucher. You should now have direct access to push to this repo.

I haven't heard back from @justinvp, but I'll add him to when/if I do.

**Comment by simonpucher** [comment]
Thanks @nikmd23, i did a merge on my fork. In the next days i will screen the changes done by the other members.

**Comment by nikmd23** [comment]
Thanks @simonpucher

**Comment by justinvp** [comment]
Unfortunately, I won't be able to get involved, but thanks for offering, @nikmd23!

**Comment by nikmd23** [comment]
No problem @justinvp. Thanks for your interest to begin with.
