### ISSUE TITLE
Please update NuGet.org with recent changes

### ISSUE THREAD

**Issue by rjmurillo** [nikmd23/CourtesyFlush#11]
NuGet.org reports version 1.1.0 last published 2014-Aug-11 http://www.nuget.org/packages/CourtesyFlush/

**Comment by nikmd23** [comment]
Hey @rjmurillo!

Thanks for pinging me, letting me know you're ready for a release. I was on vacation last week, but I'm back in the fold and will try to get a build out today or tomorrow.

**Comment by nikmd23** [comment]
I've released [CourtesyFlush 1.2.0 on NuGet](https://www.nuget.org/packages/CourtesyFlush/1.2.0).
