### ISSUE TITLE
Lost chunks on Azure

### ISSUE THREAD

**Issue by mitja-p** [nikmd23/CourtesyFlush#13]
Hi,

I do not know where is the problem, but I am occasionally getting page loaded with only header on Azure websites (https with gzip). It seems as the first chunk with head arrives but that's it. After one or two reloads everything works fine and is not reproducible. Any ideas?

Oh, btw. I am posting <head> without ending tag. It seems most browsers still preload styles, but I have an option to inject other styles on the fly.

**Comment by nikmd23** [comment]
Can you post the code you are using? I don't have "any ideas" based on what you've described.

**Comment by mitja-p** [comment]
I found out what the problem is. I am using Owin authentication like this:
```
      app.UseCookieAuthentication(new CookieAuthenticationOptions
      {
        AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,
        LoginPath = new PathString(LoginPath),
        SlidingExpiration = true,
        ExpireTimeSpan = TimeSpan.FromDays(30),
        Provider = new CookieAuthenticationProvider
        {
          OnValidateIdentity = SecurityStampValidator.OnValidateIdentity<ApplicationUserManager, ApplicationUser>(
              validateInterval: TimeSpan.FromMinutes(0/*30*/), // 30 minutes
              regenerateIdentity: (manager, user) => user.GenerateUserIdentityAsync(manager))
        }
      });
      app.UseExternalSignInCookie(DefaultAuthenticationTypes.ExternalCookie);
```
As you can see, I set validateInterval to 0 and now the problem is visible on every request. It seems like Authentication mechanism is trying to set a cookie after the flushing of the head.

Stack from the error:
```
System.Web.HttpException (0x80004005): Server cannot append header after HTTP headers have been sent.
   at System.Web.HttpHeaderCollection.SetHeader(String name, String value, Boolean replace)
   at Microsoft.Owin.Host.SystemWeb.CallHeaders.AspNetResponseHeaders.Set(String key, String[] values)
   at Microsoft.Owin.Infrastructure.OwinHelpers.AppendHeaderUnmodified(IDictionary`2 headers, String key, String[] values)
   at Microsoft.Owin.Infrastructure.ChunkingCookieManager.AppendResponseCookie(IOwinContext context, String key, String value, CookieOptions options)
   at Microsoft.Owin.Security.Cookies.CookieAuthenticationHandler.<ApplyResponseGrantAsync>d__f.MoveNext()
```
I currently don't have any idea yet how to force Cookies / Headers to be added to the response before the Flush.

**Comment by nikmd23** [comment]
Can you tell me a little more about what Auth middle-ware you are using? In what order is your middle-ware registered? I might send this over to the ASP.NET team to look at. I don't see any particular reason why they need to set the cookie later in the request.

**Comment by nikmd23** [comment]
Also, I'm going to close this since it isn't a CourtesyFlush issue, but please feel free to comment.

**Comment by mitja-p** [comment]
By middleware you had these in mind (in this order)?
      app.UseYahooAuthentication Owin.Security.Providers.dll, v1.20.1.0
      app.UseMicrosoftAccountAuthentication Microsoft.Owin.Security.MicrosoftAccount.dll, v3.0.1.0
      app.UseFacebookAuthentication Microsoft.Owin.Security.Facebook.dll, v3.0.1.0
      app.UseGoogleAuthentication Microsoft.Owin.Security.Google.3.0.1

I looked at the owin source code and when debbuging it seems that HttpContext.GetOwinContext().Authentication.AuthenticationResponseGrant is set however headers are not flushed with the response.

It seems like the Response.OnSendingHeaders is not called when it should be. I tried to set it manually but function is never called.

I posted this here in case anyone else would have problems. If you can contact the ASP.NET team, that would be great.
