### ISSUE TITLE
Invoking FlushHead from controller outputs GUID, works in _Layout

### ISSUE THREAD

**Issue by Christoph-Wagner** [nikmd23/CourtesyFlush#15]
I tried using CourtesyFlush.
`@Html.FlushHead()` works fine, as does getting a `HtmlHelper` instance in the controller and invoking `.Partial(…)` there.
But when I try to use `FlushHead()` in a controller action, the flushing works fine but instead of the content, it renders (a seemingly random) GUID (or Hash) string.

.NET 4.5.1, MVC5

Any advice?  

edit: If it's relevant, the controller and views are inside an area.

**Comment by Christoph-Wagner** [comment]
Okay, so the Problem is with Casette which we use to for asset bundling. I guess as it needs the information from all views, early flushing doesn't work with it, a shame :/

**Comment by nikmd23** [comment]
@Christoph-Wagner unfortunately, many .NET libraries assume a response will never be flushed. Hopefully with the addition of flushing in the next version of Razor, we'll see a bit more support for these use cases by the community.
