### ISSUE TITLE
A new AntiForgeryToken cookie is set on every request

### ISSUE THREAD

**Issue by drayfar** [nikmd23/CourtesyFlush#18]
The ControllerBaseExtension.WriteForgeryToken creates a new AntiForgeryToken cookie on every request, which breaks validation when multiple tabs are used because the cookie becomes out of sync with the hidden form input. This can be fixed by passing the existing AntiForgeryToken cookie value to AntiForgery.GetTokens. I'll submit a pull request for this change as well, let me know if it looks good to you.

**Comment by drayfar** [comment]
Looks like it got rolled in with my other pull request - sorry, new to git :)

**Comment by nikmd23** [comment]
No problem, and thanks @drayfar!
