### ISSUE TITLE
Title attribute from resx file

### ISSUE THREAD

**Issue by ryansaltuk** [nikmd23/CourtesyFlush#8]
Hi there
Would it be possible to create TitleResourceType=(typeof(Type)) and TitleResouceName="[string]" properties in the attribute, much like DataAnnotations so that we could pull the Title attribute from resource files?
Thanks
Ryan

**Comment by simonpucher** [comment]
Thx @ryansaltuk we have implemented the possibility to use data from resource files in the FlushHeadAttribute using TitleResourceName and TitleResourceType.
